baseURL= "https://aws-samples.github.io/aws-service-catalog-tools-workshop/"
staticDir= ["aws-service-catalog-tools-workshop"]
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Service Catalog Tools Workshop"
theme = "learn"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Service Catalog Tools Team"
description = "AWS Service Catalog Tools Workshop"
disableSearch = true
disableAssetsBusting = true
disableLanguageSwitchingButton = true
disableShortcutsTitle = true

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true