baseURL= "https://aws-samples.github.io/aws-service-catalog-tools-workshop/"
staticDir= ["static", "css"]
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Service Catalog Tools Workshop"
theme = "learn"
uglyurls = true
googleAnalytics = "UA-127749520-1"
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"
relativeURLs = true
canonifyURLs = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Service Catalog Tools Team"
description = "AWS Service Catalog Tools Workshop"
disableSearch = true
disableAssetsBusting = true
disableLanguageSwitchingButton = true
disableShortcutsTitle = true


[[menu.shortcuts]]
name = "<i class='fab fa-github fa-lg'></i> aws-service-catalog-factory repo"
identifier = "fgh"
url = "https://github.com/awslabs/aws-service-catalog-factory"
weight = 1

[[menu.shortcuts]]
name = "aws-service-catalog-factory docs"
identifier = "frtd"
url = "https://aws-service-catalog-factory.readthedocs.io/en/latest/"
weight = 2

[[menu.shortcuts]]
name = "<i class='fab fa-github fa-lg'></i> aws-service-catalog-puppet repo"
identifier = "pgh"
url = "https://github.com/awslabs/aws-service-catalog-puppet"
weight = 3

[[menu.shortcuts]]
name = "aws-service-catalog-puppet docs"
identifier = "prtd"
url = "https://aws-service-catalog-puppet.readthedocs.io/en/latest/"
weight = 4

[[menu.shortcuts]]
name = "201911011249"
identifier = "version"
url = "#"
weight = 5

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]


